spring:
  redis:
    database: 0
    host: 192.168.91.5
    port: 6379
    password: mredust4
    timeout: 5000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.91.5:3306/mredust-integration-project?useSSL=false&serverTimezone=UTC
    username: root
    password: mredust4

server:
  port: 4091


